server:
  port : 8091
  servlet:
    context-path: /sm-users
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
spring:
  profiles:
    active: test
---
spring:
  config:
    activate:
      on-profile: localdev
  datasource:
    url: jdbc:mysql://localhost:3306/smusers
    username: smhomeapp
    password: smhomeapp
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans : true
      event:
          merge:
            entity_copy_observer: allow
    show-sql: true  
    properties:
      hibernate.format_sql: true
jwt:
  secret : smusers
smaster:
  home:
    profilepicpath: C:\HiteshWork\SRIVN_WORKS\Dev\testdata\
    profPicFileSize: 2097152
---
spring:
  config:
    activate:
      on-profile: test    
  datasource:
    url: jdbc:h2:file:./data/demo
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  sql:
  init.mode: always
  h2:
  console:
  enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
      enable_lazy_load_no_trans : true
      event:
          merge:
            entity_copy_observer: allow
    show-sql: true  
    properties:
      hibernate.format_sql: true
jwt:
  secret : smusers
smaster:
  home:
    profilepicpath: C:\HiteshWork\SRIVN_WORKS\Dev\testdata\
    profPicFileSize: 2097152