INSERT INTO CLSN (CLSNID , CLSN_KEY) VALUES (1,'USERTYPE');
INSERT INTO CLSNVAL (CLSNID, CLSN_VALID , CLSN_VAL) VALUES (1,101,'STUDENT');
INSERT INTO CLSNVAL (CLSNID, CLSN_VALID , CLSN_VAL) VALUES (1,102,'GUARDIAN');
INSERT INTO CLSNVAL (CLSNID, CLSN_VALID , CLSN_VAL) VALUES (1,103,'TEACHER');
INSERT INTO CLSNVAL (CLSNID, CLSN_VALID , CLSN_VAL) VALUES (1,104,'STAFF');

INSERT INTO CLSN (CLSNID , CLSN_KEY) VALUES (2,'GENDER');
INSERT INTO CLSNVAL (CLSNID, CLSN_VALID , CLSN_VAL) VALUES (2,201,'MALE');
INSERT INTO CLSNVAL (CLSNID, CLSN_VALID , CLSN_VAL) VALUES (2,202,'FEMALE');

INSERT INTO CLSN (CLSNID , CLSN_KEY) VALUES (2,'DEPT');
INSERT INTO CLSNVAL (CLSNID, CLSN_VALID , CLSN_VAL) VALUES (3,301,'ELEC');
INSERT INTO CLSNVAL (CLSNID, CLSN_VALID , CLSN_VAL) VALUES (3,302,'ENG');
COMMIT;