INSERT INTO CLSN (CLSNID , CLSN_KEY) VALUES (1,'USERTYPE');
INSERT INTO CLSNVAL (CLSNID, CLSN_VALID , CLSN_VAL) VALUES (1,101,'STUDENT');
INSERT INTO CLSNVAL (CLSNID, CLSN_VALID , CLSN_VAL) VALUES (1,102,'GUARDIAN');
INSERT INTO CLSNVAL (CLSNID, CLSN_VALID , CLSN_VAL) VALUES (1,103,'TEACHER');
INSERT INTO CLSNVAL (CLSNID, CLSN_VALID , CLSN_VAL) VALUES (1,104,'STAFF');
COMMIT;